###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{ eventId }}

###
# @name createEvent
POST http://localhost:3000/events
Content-Type:  application/json

{
    "name": "First Event",
    "description": "Event test.",
    "date":"2024-09-24T00:00:00",
    "price":100
}
###

@eventId = {{ createEvent.response.body.id }}

###
PATCH  http://localhost:3000/events/{{ eventId }}
Content-Type:  application/json

{   
    "description": "Update again event test.",
    "date":"2024-09-24T00:00:00",
    "name":"Second event"  
}

###
DELETE  http://localhost:3000/events/{{ eventId }}
